services:
  dnsproxy:
    build: .
    container_name: dnsproxy
    cap_add: [ "NET_BIND_SERVICE" ]
    ports:
      - "53:53/udp"
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./data:/app/data        # <-- больше не затираем /app
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
