// <auto-generated />
using System;
using DnsProxy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DnsProxy.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250514223730_initKey")]
    partial class initKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DnsProxy.Models.DnsConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strategy")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ConfigDns");
                });

            modelBuilder.Entity("DnsProxy.Models.DnsRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DomainPattern")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExcludeServers")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ForceServerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IncludeServers")
                        .HasColumnType("TEXT");

                    b.Property<string>("RewriteIp")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceIp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ForceServerId");

                    b.ToTable("Rules");
                });

            modelBuilder.Entity("DnsProxy.Models.DnsServerEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Protocol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StaticAddress")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("DnsProxy.Models.VisitStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientIp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rcode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Upstream")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("DnsProxy.Models.DnsRule", b =>
                {
                    b.HasOne("DnsProxy.Models.DnsServerEntry", "ForceServer")
                        .WithMany()
                        .HasForeignKey("ForceServerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ForceServer");
                });
#pragma warning restore 612, 618
        }
    }
}
